import assert from "node:assert/strict";
import { chromium } from "playwright";
import fs from "node:fs";
import prisma from "../src/shared/db";
import { assertTestDatabaseSafety } from "./test-safety";
import { createSession } from "../src/modules/identity/session";
import { calcCost } from "../src/modules/cost-engine";
import { buildCostInput } from "../src/app/products/[id]/cost-form";
const base = process.env.UI_BASE_URL || "http://127.0.0.1:3235";
async function main() {
  assertTestDatabaseSafety();
  const tag = `safe-import-${Date.now()}`;
  const org = await prisma.organization.create({ data: { code: tag, name: "安全移植验收夹具" } });
  const owner = await prisma.user.create({ data: { email: `${tag}@test.local`, name: "负责人夹具", organizationId: org.id } });
  const viewer = await prisma.user.create({ data: { email: `${tag}-viewer@test.local`, name: "只读夹具", organizationId: org.id } });
  const product = await prisma.product.create({ data: { organizationId: org.id, name: "验收产品", identityCode: tag, targetAudience: "测试", marketPath: "测试", devMode: "NEW_PRODUCT" } });
  const project = await prisma.project.create({ data: { organizationId: org.id, title: "安全移植验收项目", target: "验证真实状态", ownerId: owner.id, productId: product.id } });
  await prisma.projectMember.createMany({ data: [{ projectId: project.id, userId: owner.id, role: "OWNER" }, { projectId: project.id, userId: viewer.id, role: "VIEWER" }] });
  const first = await prisma.workItem.create({ data: { projectId: project.id, title: "已提交报价", target: "验收", deliverableReq: "实际成果", status: "SUBMITTED", inputRevision: 2 } });
  await prisma.workItem.create({ data: { projectId: project.id, title: "等待报价验收后采购", target: "依赖", deliverableReq: "订单", status: "TODO", dependencies: [first.id], inputRevision: 1 } });
  const emptyProject = await prisma.project.create({ data: { organizationId: org.id, title: "尚无工作项的关联项目", target: "验证多项目选择", ownerId: owner.id, productId: product.id } });
  await prisma.projectMember.create({ data: { projectId: emptyProject.id, userId: owner.id, role: "OWNER" } });
  const tokens = { owner: (await createSession(owner.id)).token, viewer: (await createSession(viewer.id)).token };
  const chrome = process.env.CHROME_PATH || ["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", chromium.executablePath()].find(path => fs.existsSync(path));
  const browser = await chromium.launch({ executablePath: chrome, args: ["--no-sandbox", "--no-proxy-server"] });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const setUser = async (token: string) => {
    await context.clearCookies();
    await context.addCookies([{ name: "hermes_session_token", value: token, url: base }]);
  };
  try {
    await setUser(tokens.owner);
    await page.goto(`${base}/projects/${project.id}`);
    const brief = page.getByRole("region", { name: "项目工作简报" });
    await brief.waitFor();
    assert.match(await brief.innerText(), /0 \/ 2/);
    assert.match(await brief.innerText(), /1 个待办的依赖尚未满足/);
    await page.getByRole("button", { name: "销售经营", exact: true }).click();
    await page.reload();
    await page.waitForFunction(() => document.querySelector('.kern-perspective button[aria-pressed="true"]')?.textContent === "销售经营");
    await page.goto(`${base}/muse`);
    await page.waitForFunction(() => document.querySelector('.kern-perspective button[aria-pressed="true"]')?.textContent === "销售经营");
    assert.equal(await page.getByRole("region", { name: "当前工作简报" }).count(), 1);
    assert.equal(await page.locator(".kern-home-brief").count(), 1);
    assert.ok(await page.evaluate(() => {
      const heading = document.querySelector(".m-home-head");
      const summary = document.querySelector(".kern-home-brief");
      return Boolean(heading && summary && heading.compareDocumentPosition(summary) & Node.DOCUMENT_POSITION_FOLLOWING);
    }), "greeting precedes summary");
    console.log("PASS role selection → reload → Muse shares the account preference; one summary below greeting");
    await page.goto(`${base}/projects/${project.id}`);
    await page.getByRole("tab", { name: "成本情景", exact: true }).click();
    await page.getByLabel("保存到工作项").selectOption(first.id);
    const fields: [string, string][] = [["直接材料成本（元/件）", "8"], ["外包装成本（元/件）", "1"], ["制造成本（元/件）", "2"], ["认证成本（元/件）", "0.5"], ["月固定成本（元/月）", "1000"], ["含税零售价（元/件）", "69"]];
    for (const [label, value] of fields) await page.getByLabel(label, { exact: false }).fill(value);
    await page.getByRole("button", { name: "计算经济性" }).click();
    await page.waitForFunction(() => document.activeElement?.getAttribute("aria-label") === "成本计算结果");
    assert.equal(await page.locator(".kern-cost-metrics dd").count(), 4);
    await page.getByLabel("直接材料成本（元/件）", { exact: false }).fill("9");
    assert.equal(await page.locator(".kern-cost-metrics").count(), 0, "editing input invalidates old result");
    assert.equal(await page.getByRole("button", { name: "保存情景", exact: true }).count(), 0, "stale results cannot be saved");
    await page.getByLabel("直接材料成本（元/件）", { exact: false }).fill("8");
    const assumptions = page.locator(".kern-cost-assumptions summary");
    await assumptions.focus();
    await page.keyboard.press("Enter");
    assert.equal(await page.locator(".kern-cost-assumptions").getAttribute("open"), "");
    assert.ok(await page.getByLabel("达人佣金率 %（可覆盖预设）").isVisible());
    await assumptions.focus(); await page.keyboard.press("Enter");
    await page.getByRole("button", { name: "计算经济性" }).click();
    console.log("PASS modular cost form → result focus; edits invalidate result; assumptions expand by keyboard");
    await page.getByRole("textbox", { name: "情景名称" }).fill("安全移植情景");
    const reply = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith(`/api/products/${product.id}/cost-scenarios`));
    await page.getByRole("button", { name: "保存情景", exact: true }).click();
    const saved = await reply;
    assert.equal(saved.status(), 201, await saved.text());
    const result = await saved.json();
    const artifact = await prisma.artifact.findUniqueOrThrow({ where: { id: result.artifactId } });
    assert.equal(artifact.workItemId, first.id, "record must point to a WorkItem, never a project id");
    assert.equal(artifact.inputRevision, 2);
    assert.equal(JSON.parse(artifact.content).projectId, project.id);
    assert.equal(JSON.parse(artifact.content).productId, product.id);
    const input = buildCostInput({ materialCost: "8", packagingCost: "1", manufacturingCost: "2", certificationCost: "0.5", monthlyFixed: "1000", retailPrice: "69", channel: "XINXUAN", invoiceType: "达人开票", expressType: "STANDARD" });
    assert.equal(result.recalculatedResult.totalCost, calcCost(input).totalCost);
    await page.reload();
    await page.getByRole("tab", { name: "成本情景", exact: true }).click();
    await page.getByRole("button", { name: "载入情景：安全移植情景", exact: true }).click();
    assert.equal(await page.getByLabel("直接材料成本（元/件）", { exact: false }).inputValue(), "8");
    console.log("PASS cost UI → real API → artifact workItem → server recalculation → reload/restore");
    await page.goto(`${base}/products/${product.id}?tab=cost`);
    await page.getByRole("button", { name: "载入情景：安全移植情景", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "保存情景", exact: true }).count(), 0, "no silent workItem selection");
    await page.getByLabel("成本成果记录到", { exact: false }).selectOption(first.id);
    assert.equal(await page.getByRole("link", { name: "打开成本成果所属项目：安全移植验收项目" }).getAttribute("href"), `/projects/${project.id}`);
    await page.getByRole("textbox", { name: "情景名称" }).fill("产品页真实工作项");
    const productReply = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith(`/api/products/${product.id}/cost-scenarios`));
    await page.getByRole("button", { name: "保存情景", exact: true }).click();
    const productSaved = await productReply;
    assert.equal(productSaved.status(), 201, await productSaved.text());
    const productResult = await productSaved.json();
    const productArtifact = await prisma.artifact.findUniqueOrThrow({ where: { id: productResult.artifactId } });
    assert.equal(productArtifact.workItemId, first.id);
    console.log("PASS existing product cost page also saves against a real workItem");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`${base}/projects/${project.id}`);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth <= 1), "mobile overflow");
    await page.getByRole("tab", { name: "成本情景", exact: true }).click();
    await page.getByLabel("直接材料成本（元/件）", { exact: false }).waitFor();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), "mobile cost overflow");
    for (const selector of [".kern-cost-workbench .hermes-input", ".kern-cost-workbench .hermes-select"]) {
      const heights = await page.locator(selector).evaluateAll(elements => elements.filter(element => element.getBoundingClientRect().height > 0).map(element => element.getBoundingClientRect().height));
      assert.ok(heights.every(height => height >= 44), "cost controls need touch space");
    }
    console.log("PASS mobile overview/cost has no horizontal overflow; visible inputs meet 44px touch size");
    await setUser(tokens.viewer);
    await page.goto(`${base}/projects/${project.id}`);
    await page.waitForFunction(() => document.querySelector('.kern-perspective button[aria-pressed="true"]')?.textContent === "负责人");
    const denied = await context.request.post(`${base}/api/products/${product.id}/cost-scenarios`, { data: { scenarioName: "越权", costInput: input, sourceStatus: "DRAFT", unit: "件", currency: "CNY", expenseBase: "出厂口径", workItemId: first.id } });
    assert.equal(denied.status(), 403);
    assert.equal(await prisma.artifact.count({ where: { workItemId: first.id, title: "越权" } }), 0);
    console.log("PASS another account has its own perspective; VIEWER save denied and no artifact created");
    assert.deepEqual(errors, []);
  } finally {
    await browser.close();
    await prisma.artifact.deleteMany({ where: { organizationId: org.id } });
    await prisma.workItem.deleteMany({ where: { projectId: project.id } });
    await prisma.projectMember.deleteMany({ where: { project: { organizationId: org.id } } });
    await prisma.project.deleteMany({ where: { organizationId: org.id } });
    await prisma.product.delete({ where: { id: product.id } });
    await prisma.session.deleteMany({ where: { userId: { in: [owner.id, viewer.id] } } });
    await prisma.user.deleteMany({ where: { organizationId: org.id } });
    await prisma.organization.delete({ where: { id: org.id } });
    await prisma.$disconnect();
  }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
