-- 研究基座 P7 的 ResearchRun 状态机：抓取中/成功/无可用源阻断
-- 原枚举只有 RUNNING/PUBLISHED/FAILED，代码已按 PENDING/SUCCEEDED/BLOCKED 判定
ALTER TYPE "ResearchRunStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "ResearchRunStatus" ADD VALUE IF NOT EXISTS 'SUCCEEDED';
ALTER TYPE "ResearchRunStatus" ADD VALUE IF NOT EXISTS 'BLOCKED';
